"""initial schema

Revision ID: b8d46f50707c
Revises:
Create Date: 2026-07-08 11:05:26.287311
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b8d46f50707c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_prompts",
        sa.Column(
            "id",
            sa.Enum(
                "ingestor",
                "comprehension",
                "planner",
                "scriptwriter",
                "visual_designer",
                "narrator",
                "verifier",
                "assembler",
                name="agent_id",
            ),
            nullable=False,
        ),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("default_template", sa.Text(), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "install_meta",
        sa.Column("id", sa.Boolean(), nullable=False),
        sa.Column("encryption_salt", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id", name="ck_install_meta_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_paper", sa.Text(), nullable=False),
        sa.Column("paper_file_url", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "generating", "ready", "failed", name="project_status"),
            nullable=False,
        ),
        sa.Column(
            "audience",
            sa.Enum("layperson", "student", "expert", name="audience_level"),
            nullable=False,
        ),
        sa.Column(
            "aspect_ratio", sa.Enum("16:9", "9:16", "1:1", name="aspect_ratio"), nullable=False
        ),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("target_length_min", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provider_connections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "openai", "anthropic", "elevenlabs", "ollama", "gemini", "groq", name="provider_id"
            ),
            nullable=False,
        ),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("api_key_enc", sa.LargeBinary(), nullable=True),
        sa.Column("api_key_masked", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("unknown", "ok", "error", name="connection_status"), nullable=False
        ),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "render_settings",
        sa.Column("id", sa.Boolean(), nullable=False),
        sa.Column("fps", sa.SmallInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("quality", sa.SmallInteger(), nullable=False),
        sa.Column("format", sa.Enum("mp4", "webm", name="video_format"), nullable=False),
        sa.Column(
            "codec", sa.Enum("h264", "h265", "vp9", "av1", name="video_codec"), nullable=False
        ),
        sa.Column("gpu", sa.Boolean(), nullable=False),
        sa.Column("workers", sa.SmallInteger(), nullable=False),
        sa.Column("audio_master_db", sa.Float(), nullable=False),
        sa.Column("audio_narration_db", sa.Float(), nullable=False),
        sa.Column("audio_music_db", sa.Float(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("fps IN (24, 30, 60)", name="ck_render_fps"),
        sa.CheckConstraint("id", name="ck_render_settings_singleton"),
        sa.CheckConstraint("quality BETWEEN 0 AND 100", name="ck_render_quality"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_model_assignments",
        sa.Column(
            "role",
            sa.Enum(
                "comprehension",
                "planner",
                "scriptwriter",
                "visual_designer",
                "narrator",
                "verifier",
                name="agent_role",
            ),
            nullable=False,
        ),
        sa.Column("connection_id", sa.String(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["provider_connections.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("role"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "done", "error", name="agent_status"),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("procrastinate_job_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_runs_project_id"), "pipeline_runs", ["project_id"], unique=False
    )
    op.create_table(
        "render_jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "done", "error", name="render_status"),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("output_url", sa.Text(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_render_jobs_project_id"), "render_jobs", ["project_id"], unique=False)
    op.create_table(
        "scenes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column(
            "visual_type",
            sa.Enum(
                "title.card",
                "bullet.reveal",
                "figure.callout",
                "equation.build",
                "dataviz.bar",
                "diagram.attention",
                "comparison.split",
                "kinetic.type",
                name="visual_type",
            ),
            nullable=False,
        ),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "caption_style",
            sa.Enum("none", "minimal", "bold", name="caption_style"),
            nullable=False,
        ),
        sa.Column(
            "transition",
            sa.Enum("cut", "fade", "slide", "wipe", name="scene_transition"),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "position", name="uq_scene_position"),
    )
    op.create_index(op.f("ix_scenes_project_id"), "scenes", ["project_id"], unique=False)
    op.create_table(
        "agent_node_states",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column(
            "agent",
            sa.Enum(
                "ingestor",
                "comprehension",
                "planner",
                "scriptwriter",
                "visual_designer",
                "narrator",
                "verifier",
                "assembler",
                name="agent_id",
            ),
            nullable=False,
        ),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "done", "error", name="agent_status"),
            nullable=False,
        ),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "agent", name="uq_agent_node"),
    )
    op.create_index(
        op.f("ix_agent_node_states_run_id"), "agent_node_states", ["run_id"], unique=False
    )
    op.create_table(
        "pipeline_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "agent",
            sa.Enum(
                "ingestor",
                "comprehension",
                "planner",
                "scriptwriter",
                "visual_designer",
                "narrator",
                "verifier",
                "assembler",
                name="agent_id",
            ),
            nullable=True,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_events_run_id"), "pipeline_events", ["run_id"], unique=False)
    op.create_table(
        "scene_citations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("scene_id", sa.String(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("source_span", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scene_citations_scene_id"), "scene_citations", ["scene_id"], unique=False
    )
    op.create_table(
        "verifier_flags",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("source_span", sa.Text(), nullable=False),
        sa.Column("level", sa.Enum("pass", "warn", "fail", name="verifier_level"), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verifier_flags_project_id"), "verifier_flags", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verifier_flags_project_id"), table_name="verifier_flags")
    op.drop_table("verifier_flags")
    op.drop_index(op.f("ix_scene_citations_scene_id"), table_name="scene_citations")
    op.drop_table("scene_citations")
    op.drop_index(op.f("ix_pipeline_events_run_id"), table_name="pipeline_events")
    op.drop_table("pipeline_events")
    op.drop_index(op.f("ix_agent_node_states_run_id"), table_name="agent_node_states")
    op.drop_table("agent_node_states")
    op.drop_index(op.f("ix_scenes_project_id"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_render_jobs_project_id"), table_name="render_jobs")
    op.drop_table("render_jobs")
    op.drop_index(op.f("ix_pipeline_runs_project_id"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_table("agent_model_assignments")
    op.drop_table("render_settings")
    op.drop_table("provider_connections")
    op.drop_table("projects")
    op.drop_table("install_meta")
    op.drop_table("agent_prompts")
    # ### end Alembic commands ###
