// Typed API service layer — real REST + SSE calls to the Vyakhya backend.
// Screens import these functions unchanged; the wire contract is docs/api.md.

import { compile, type SceneDocument, type SceneNode } from "@vyakhya/compiler";

import type {
  AgentId,
  AgentModelAssignment,
  AgentPrompt,
  AgentSettings,
  ConnectionTestResult,
  EditorProject,
  PipelineEvent,
  Project,
  ProviderConnection,
  ProviderId,
  RenderJob,
  RenderSettings,
  Scene,
  VerifierFlag,
} from "./types";

// Same-origin in production (the backend serves the built frontend); the dev
// server talks to the API on :8000. Override with VITE_API_URL.
const API_BASE: string =
  (import.meta.env.VITE_API_URL as string | undefined) ??
  (import.meta.env.DEV ? "http://localhost:8000" : "");

// Optional API key (generated by ./setup.sh). Sent on every request as a header.
const API_KEY: string | undefined = import.meta.env.VITE_API_KEY as string | undefined;

const apiUrl = (path: string) => `${API_BASE}/api${path}`;

function authHeaders(base: Record<string, string> = {}): Record<string, string> {
  return API_KEY ? { ...base, "X-API-Key": API_KEY } : base;
}

// True only in the browser. During SSR/SPA-shell prerender there is no backend,
// so network calls are skipped (queries stay pending → the static shell renders
// its loading state; the client fetches for real after hydration).
const IS_BROWSER = typeof window !== "undefined";

async function http<T>(path: string, init?: RequestInit): Promise<T> {
  if (!IS_BROWSER) return new Promise<T>(() => {}); // never resolves during prerender
  const isJson = init?.body && !(init.body instanceof FormData);
  const res = await fetch(apiUrl(path), {
    ...init,
    headers: authHeaders(isJson ? { "content-type": "application/json" } : {}),
  });
  if (!res.ok) {
    throw new Error(`${res.status} ${res.statusText}`);
  }
  if (res.status === 204) return undefined as T;
  return (await res.json()) as T;
}

// Shared fetch-based SSE reader (works for GET and POST, and carries the auth
// header — which EventSource cannot). Returns an unsubscribe function.
function streamSSE(path: string, init: RequestInit, onEvent: (event: unknown) => void): () => void {
  if (!IS_BROWSER) return () => {};
  const ctrl = new AbortController();
  (async () => {
    const res = await fetch(apiUrl(path), {
      ...init,
      headers: authHeaders(init.headers as Record<string, string>),
      signal: ctrl.signal,
    });
    if (!res.body) return;
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      let idx: number;
      while ((idx = buffer.indexOf("\n\n")) >= 0) {
        const frame = buffer.slice(0, idx);
        buffer = buffer.slice(idx + 2);
        const dataLine = frame.split("\n").find((l) => l.startsWith("data:"));
        if (dataLine) {
          try {
            onEvent(JSON.parse(dataLine.slice(5).trim()));
          } catch {
            /* ignore malformed frame */
          }
        }
      }
    }
  })().catch(() => {
    /* aborted or network error */
  });
  return () => ctrl.abort();
}

// ---------------- Projects ----------------
export function listProjects(): Promise<Project[]> {
  return http<Project[]>("/projects");
}

export async function getProject(id: string): Promise<Project | undefined> {
  try {
    return await http<Project>(`/projects/${id}`);
  } catch {
    return undefined;
  }
}

export function createProject(input: {
  file: File;
  audience: Project["audience"];
  aspectRatio: Project["aspectRatio"];
  language: string;
  targetLengthMin: number;
  ttsEnabled: boolean;
  userPrompt?: string;
}): Promise<Project> {
  const form = new FormData();
  form.append("file", input.file);
  form.append("audience", input.audience);
  form.append("aspectRatio", input.aspectRatio);
  form.append("language", input.language);
  form.append("targetLengthMin", String(input.targetLengthMin));
  form.append("ttsEnabled", String(input.ttsEnabled));
  if (input.userPrompt?.trim()) form.append("userPrompt", input.userPrompt.trim());
  return http<Project>("/projects", { method: "POST", body: form });
}

export function deleteProject(id: string): Promise<void> {
  return http<void>(`/projects/${id}`, { method: "DELETE" });
}

// ---------------- Pipeline ----------------
const AGENT_SEQUENCE: { id: AgentId; label: string }[] = [
  { id: "ingestor", label: "Ingestor" },
  { id: "visual_designer", label: "Visual Designer" },
  { id: "narrator", label: "Narrator" },
  { id: "verifier", label: "Reviewer" },
  { id: "assembler", label: "Assembler" },
];

export function getAgentSequence() {
  return AGENT_SEQUENCE;
}

// Subscribe to the pipeline SSE stream. Idempotent server-side: attaches to an
// in-flight run (with replay) instead of starting a new one; `restart` forces a
// fresh run when the latest one has finished. Returns an unsubscribe function.
export function subscribePipeline(
  projectId: string,
  onEvent: (event: PipelineEvent) => void,
  opts?: { restart?: boolean },
): () => void {
  const qs = opts?.restart ? "?restart=true" : "";
  return streamSSE(`/projects/${projectId}/pipeline/stream${qs}`, { method: "GET" }, (e) =>
    onEvent(e as PipelineEvent),
  );
}

export function getVerifierFlags(projectId: string): Promise<VerifierFlag[]> {
  return http<VerifierFlag[]>(`/projects/${projectId}/verifier-flags`);
}

// ---------------- Editor ----------------
export function getEditorProject(id: string): Promise<EditorProject> {
  return http<EditorProject>(`/projects/${id}/editor`);
}

export function saveScene(projectId: string, scene: Scene): Promise<Scene> {
  return http<Scene>(`/projects/${projectId}/scenes/${scene.id}`, {
    method: "PUT",
    body: JSON.stringify(scene),
  });
}

// Live preview compiles client-side via the shared @vyakhya/compiler — the same
// compiler the render worker uses, so preview == final. No round-trip.
export function compileScenePreview(scene: Scene): Promise<string> {
  const doc: SceneDocument = {
    id: "preview",
    title: "Preview",
    aspectRatio: "16:9",
    scenes: [scene as unknown as SceneNode],
  };
  return Promise.resolve(compile(doc, { fit: true }));
}

// Compile the whole project into a single seekable preview composition — the
// scrubber/playhead drives which scene shows and animates (see PreviewPlayer).
export function compileProjectPreview(project: EditorProject): string {
  const doc: SceneDocument = {
    id: project.id,
    title: project.title,
    aspectRatio: project.aspectRatio,
    scenes: project.scenes as unknown as SceneNode[],
  };
  return compile(doc, { preview: true });
}

// ---------------- Model config ----------------
export function listConnections(): Promise<ProviderConnection[]> {
  return http<ProviderConnection[]>("/connections");
}

export interface ConnectionInput {
  provider: ProviderId;
  model: string;
  apiKey: string;
  baseUrl?: string;
  settings?: Record<string, unknown>;
}

export function addConnection(c: ConnectionInput): Promise<ProviderConnection> {
  return http<ProviderConnection>("/connections", {
    method: "POST",
    body: JSON.stringify(c),
  });
}

export interface ConnectionUpdateInput {
  model?: string;
  apiKey?: string; // blank/omitted keeps the stored key
  baseUrl?: string;
  settings?: Record<string, unknown>;
}

export function updateConnection(
  id: string,
  c: ConnectionUpdateInput,
): Promise<ProviderConnection> {
  return http<ProviderConnection>(`/connections/${id}`, {
    method: "PUT",
    body: JSON.stringify(c),
  });
}

export function removeConnection(id: string): Promise<void> {
  return http<void>(`/connections/${id}`, { method: "DELETE" });
}

export function testConnection(id: string): Promise<ConnectionTestResult> {
  return http<ConnectionTestResult>(`/connections/${id}/test`, { method: "POST" });
}

// Probe an unsaved connection straight from the add-connection form.
export function testConnectionDraft(c: ConnectionInput): Promise<ConnectionTestResult> {
  return http<ConnectionTestResult>("/connections/test", {
    method: "POST",
    body: JSON.stringify(c),
  });
}

export function listAssignments(): Promise<AgentModelAssignment[]> {
  return http<AgentModelAssignment[]>("/assignments");
}

export function updateAssignment(
  role: AgentModelAssignment["role"],
  connectionId: string | null,
): Promise<AgentModelAssignment[]> {
  return http<AgentModelAssignment[]>(`/assignments/${role}`, {
    method: "PUT",
    body: JSON.stringify({ connectionId }),
  });
}

// ---------------- Prompts ----------------
export function listPrompts(): Promise<AgentPrompt[]> {
  return http<AgentPrompt[]>("/prompts");
}

export function savePrompt(id: AgentId, template: string): Promise<AgentPrompt> {
  return http<AgentPrompt>(`/prompts/${id}`, {
    method: "PUT",
    body: JSON.stringify({ template }),
  });
}

export function resetPrompt(id: AgentId): Promise<AgentPrompt> {
  return http<AgentPrompt>(`/prompts/${id}/reset`, { method: "POST" });
}

// ---------------- Render ----------------
export function getRenderSettings(): Promise<RenderSettings> {
  return http<RenderSettings>("/render/settings");
}

export function saveRenderSettings(s: RenderSettings): Promise<RenderSettings> {
  return http<RenderSettings>("/render/settings", {
    method: "PUT",
    body: JSON.stringify(s),
  });
}

export function getAgentSettings(): Promise<AgentSettings> {
  return http<AgentSettings>("/agents/settings");
}

export function saveAgentSettings(s: AgentSettings): Promise<AgentSettings> {
  return http<AgentSettings>("/agents/settings", {
    method: "PUT",
    body: JSON.stringify(s),
  });
}

// Start a background render for the project; returns the job immediately.
// Progress is streamed separately via subscribeRenderJob (survives reloads).
export function startRender(projectId: string, settings?: RenderSettings): Promise<RenderJob> {
  return http<RenderJob>(`/projects/${projectId}/render`, {
    method: "POST",
    body: JSON.stringify(settings ?? null),
  });
}

export function listRenders(projectId: string): Promise<RenderJob[]> {
  return http<RenderJob[]>(`/projects/${projectId}/renders`);
}

// Live job progress (SSE over the persisted job state). Returns unsubscribe.
export function subscribeRenderJob(jobId: string, onEvent: (job: RenderJob) => void): () => void {
  return streamSSE(`/renders/${jobId}/stream`, { method: "GET" }, (e) => onEvent(e as RenderJob));
}

// ---------------- Visual type schemas ----------------
// Drives the schema-driven params form in the editor inspector.
export interface ParamField {
  key: string;
  label: string;
  kind: "text" | "textarea" | "number" | "list" | "bars";
  placeholder?: string;
}

export const visualTypeSchemas: Record<
  string,
  { label: string; description: string; fields: ParamField[] }
> = {
  "title.card": {
    label: "Title card",
    description: "Opening title with subtitle.",
    fields: [
      { key: "title", label: "Title", kind: "text" },
      { key: "subtitle", label: "Subtitle", kind: "text" },
    ],
  },
  "bullet.reveal": {
    label: "Bullet reveal",
    description: "Bullets revealed one at a time.",
    fields: [{ key: "bullets", label: "Bullets (one per line)", kind: "list" }],
  },
  "figure.callout": {
    label: "Figure callout",
    description: "Highlight a figure from the paper.",
    fields: [
      { key: "caption", label: "Caption", kind: "text" },
      { key: "figureRef", label: "Figure reference", kind: "text", placeholder: "e.g. Fig. 3" },
    ],
  },
  "equation.build": {
    label: "Equation build",
    description: "Progressive equation reveal.",
    fields: [
      {
        key: "latex",
        label: "LaTeX",
        kind: "textarea",
        placeholder: "\\text{softmax}(QK^T/\\sqrt{d_k})V",
      },
    ],
  },
  "dataviz.bar": {
    label: "Bar chart",
    description: "Simple comparison bars.",
    fields: [{ key: "series", label: "Series (label,value per line)", kind: "bars" }],
  },
  "diagram.attention": {
    label: "Attention diagram",
    description: "Token-to-token attention lines.",
    fields: [{ key: "tokens", label: "Tokens (one per line)", kind: "list" }],
  },
  "comparison.split": {
    label: "Comparison split",
    description: "Side-by-side comparison.",
    fields: [
      { key: "left", label: "Left", kind: "text" },
      { key: "right", label: "Right", kind: "text" },
    ],
  },
  "kinetic.type": {
    label: "Kinetic typography",
    description: "Animated single-word emphasis.",
    fields: [{ key: "text", label: "Text", kind: "text" }],
  },
  "orbit.3d": {
    label: "3D concept orbit",
    description: "Key concepts orbiting on a rotating 3D ring.",
    fields: [{ key: "tokens", label: "Concepts (one per line)", kind: "list" }],
  },
  "custom.html": {
    label: "Custom scene",
    description:
      "Agent-authored HTML/CSS stage. Animations must be finite and offset by calc(var(--t0) + …) to stay seekable.",
    fields: [
      { key: "html", label: "HTML", kind: "textarea" },
      { key: "css", label: "CSS", kind: "textarea" },
    ],
  },
};

// Presigned URL of the project's original PDF (for 'View source' links).
export function getPaperUrl(projectId: string): Promise<{ url: string }> {
  return http<{ url: string }>(`/projects/${projectId}/paper`);
}
