/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenderSettingsRouteImport } from './routes/render-settings'
import { Route as ModelConfigRouteImport } from './routes/model-config'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentPromptsRouteImport } from './routes/agent-prompts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdPipelineRouteImport } from './routes/projects.$projectId.pipeline'
import { Route as ProjectsProjectIdEditorRouteImport } from './routes/projects.$projectId.editor'

const RenderSettingsRoute = RenderSettingsRouteImport.update({
  id: '/render-settings',
  path: '/render-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelConfigRoute = ModelConfigRouteImport.update({
  id: '/model-config',
  path: '/model-config',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPromptsRoute = AgentPromptsRouteImport.update({
  id: '/agent-prompts',
  path: '/agent-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdPipelineRoute =
  ProjectsProjectIdPipelineRouteImport.update({
    id: '/projects/$projectId/pipeline',
    path: '/projects/$projectId/pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdEditorRoute = ProjectsProjectIdEditorRouteImport.update({
  id: '/projects/$projectId/editor',
  path: '/projects/$projectId/editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-prompts': typeof AgentPromptsRoute
  '/dashboard': typeof DashboardRoute
  '/model-config': typeof ModelConfigRoute
  '/render-settings': typeof RenderSettingsRoute
  '/projects/$projectId/editor': typeof ProjectsProjectIdEditorRoute
  '/projects/$projectId/pipeline': typeof ProjectsProjectIdPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-prompts': typeof AgentPromptsRoute
  '/dashboard': typeof DashboardRoute
  '/model-config': typeof ModelConfigRoute
  '/render-settings': typeof RenderSettingsRoute
  '/projects/$projectId/editor': typeof ProjectsProjectIdEditorRoute
  '/projects/$projectId/pipeline': typeof ProjectsProjectIdPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-prompts': typeof AgentPromptsRoute
  '/dashboard': typeof DashboardRoute
  '/model-config': typeof ModelConfigRoute
  '/render-settings': typeof RenderSettingsRoute
  '/projects/$projectId/editor': typeof ProjectsProjectIdEditorRoute
  '/projects/$projectId/pipeline': typeof ProjectsProjectIdPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-prompts'
    | '/dashboard'
    | '/model-config'
    | '/render-settings'
    | '/projects/$projectId/editor'
    | '/projects/$projectId/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-prompts'
    | '/dashboard'
    | '/model-config'
    | '/render-settings'
    | '/projects/$projectId/editor'
    | '/projects/$projectId/pipeline'
  id:
    | '__root__'
    | '/'
    | '/agent-prompts'
    | '/dashboard'
    | '/model-config'
    | '/render-settings'
    | '/projects/$projectId/editor'
    | '/projects/$projectId/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentPromptsRoute: typeof AgentPromptsRoute
  DashboardRoute: typeof DashboardRoute
  ModelConfigRoute: typeof ModelConfigRoute
  RenderSettingsRoute: typeof RenderSettingsRoute
  ProjectsProjectIdEditorRoute: typeof ProjectsProjectIdEditorRoute
  ProjectsProjectIdPipelineRoute: typeof ProjectsProjectIdPipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/render-settings': {
      id: '/render-settings'
      path: '/render-settings'
      fullPath: '/render-settings'
      preLoaderRoute: typeof RenderSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-config': {
      id: '/model-config'
      path: '/model-config'
      fullPath: '/model-config'
      preLoaderRoute: typeof ModelConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-prompts': {
      id: '/agent-prompts'
      path: '/agent-prompts'
      fullPath: '/agent-prompts'
      preLoaderRoute: typeof AgentPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/pipeline': {
      id: '/projects/$projectId/pipeline'
      path: '/projects/$projectId/pipeline'
      fullPath: '/projects/$projectId/pipeline'
      preLoaderRoute: typeof ProjectsProjectIdPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/editor': {
      id: '/projects/$projectId/editor'
      path: '/projects/$projectId/editor'
      fullPath: '/projects/$projectId/editor'
      preLoaderRoute: typeof ProjectsProjectIdEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentPromptsRoute: AgentPromptsRoute,
  DashboardRoute: DashboardRoute,
  ModelConfigRoute: ModelConfigRoute,
  RenderSettingsRoute: RenderSettingsRoute,
  ProjectsProjectIdEditorRoute: ProjectsProjectIdEditorRoute,
  ProjectsProjectIdPipelineRoute: ProjectsProjectIdPipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
